aq<- datasets::airquality
mean(aq$Ozone,na.rm=T)
mean(aq$Solar.R,na.rm=T)
mean(aq$Wind)
mean(aq$Temp)
mean(aq$Month)
mean(aq$Day)
var(aq$Ozone,na.rm=T)
var(aq$Solar.R,na.rm=T)
var(aq$Wind)
var(aq$Temp)
var(aq$Month)
var(aq$Day)
sd(aq$Ozone,na.rm=T)
sd(aq$Solar.R,na.rm=T)
sd(aq$Wind)
sd(aq$Temp)
sd(aq$Month)
sd(aq$Day)
median(aq$Ozone,na.rm=T)
median(aq$Solar.R,na.rm=T)
median(aq$Wind)
median(aq$Temp)
median(aq$Month)
median(aq$Day)
range(aq$Ozone,na.rm=T)
range(aq$Solar.R,na.rm=T)
range(aq$Wind)
ranage(aq$Temp)
ranage(aq$Month)
ranage(aq$Day)
summary(aq)


